---
- name: Display a single Ansible fact
  hosts: all
  gather_facts: true

  tasks:
    - name: Set custom variable for user
      set_fact:
        ansible_user: "{{ ansible_facts['env']['HOME'] }}"

    - name: Print the fact
      debug:
        # msg: "The fact is {{ ansible_facts['user_id'] }}"
        msg: "The fact is {{ ansible_user }}"
