---
# tasks file for template
- name: Install Foliate E-book reader
  when: ansible_facts['os_family'] == 'Debian'
  block:
    - name: Install Foliate
      become: true
      community.general.flatpak:
        name: com.github.johnfactotum.Foliate
        method: system
        state: present

    - name: Update Foliate from Flathub
      become: true
      community.general.flatpak:
        name: com.github.johnfactotum.Foliate
        method: system
        state: latest
