---
# tasks file for template
- name: Set custom variable for user
  ansible.builtin.set_fact:
    ssh_user_id: "{{ ansible_facts['user_id'] }}"

- name: Configure SSH server
  become: true
  when: ansible_facts['os_family'] == 'Debian'
  block:
    - name: Install OpenSSH server
      ansible.builtin.apt:
        name: openssh-server
        state: present

    - name: Ensure SSH service is enabled and running
      ansible.builtin.service:
        name: ssh
        state: started
        enabled: true

    - name: Create /etc/issue.net with banner message
      ansible.builtin.copy:
        content: "{{ banner_message }}"
        dest: /etc/issue.net
        owner: root
        group: root
        mode: "0644"

    - name: Ensure SSH banner is configured in sshd_config
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^Banner"
        line: "Banner /etc/issue.net"
        state: present

    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: /home/{{ ssh_user_id }}/.ssh
        state: directory
        owner: "{{ ssh_user_id }}"
        group: "{{ ssh_user_id }}"
        mode: "0700"

    - name: Push SSH config file to all hosts
      ansible.builtin.copy:
        src: config
        dest: /home/{{ ssh_user_id }}/.ssh/config
        owner: "{{ ssh_user_id }}"
        group: "{{ ssh_user_id }}"
        mode: "0644"

- name: Add Ansible SSH key to authorized_keys
  when: inventory_hostname not in groups['control'] and ansible_facts['os_family'] == 'Debian' # Dont add the key to the control host
  ansible.builtin.authorized_key:
    user: "{{ ssh_user_id }}"
    state: present
    key: "{{ ssh_ansible_key }}"

- name: Add SSH key to authorized_keys
  when: inventory_hostname not in groups['control'] and ansible_facts['os_family'] == 'Debian' # Dont add the key to the control host
  ansible.builtin.authorized_key:
    user: "{{ ssh_user_id }}"
    state: present
    key: "{{ ssh_public_key }}"
