---
# tasks file for template
- name: Install Gnome Screenshot
  when: ansible_facts['os_family'] == 'Debian'
  become: true
  block:
    - name: Ensure GNOME Screenshot is installed
      ansible.builtin.apt:
        name: gnome-screenshot
        state: present
