---
- name: Install base packages
  hosts: home
  become: false

  roles:
    # Applications
    - role: foliate
    - role: screenshot
    - role: zed
    # Services
    # - role: cifs_utils
    # - role: ssh
