---
- name: Update package cache and upgrade all packages
  tags: always
  hosts: all
  become: true

  tasks:
    - name: Update the apt package cache (Debian based)
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      changed_when: false
      when: ansible_facts['os_family'] == 'Debian'

    - name: Upgrade all packages (Debian based)
      ansible.builtin.apt:
        upgrade: dist
      when: ansible_facts['os_family'] == 'Debian'

    - name: Cleanup package cache (Debian based)
      ansible.builtin.apt:
        autoclean: yes
      changed_when: false
      when: ansible_facts['os_family'] == 'Debian'

    - name: Cleanup autoremove orphan packages (Debian based)
      ansible.builtin.apt:
        autoremove: yes
        purge: yes

    - name: Update Flatpak repository information
      command: flatpak update --appstream
      changed_when: false

    - name: Update all Flatpak packages
      command: flatpak update -y

    - name: Clean up unused runtimes
      command: flatpak uninstall --unused -y

      when: ansible_facts['os_family'] == 'Debian'
